name: Docs Site

on:
  push:
  pull_request:

jobs:
  build:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4.1.7
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: pip install -r docs/requirements.txt

      - name: Build Docs
        run: mkdocs build

      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: docs
          path: site

  publish_pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Download Docs Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: docs
          path: docs

      - name: Fix File Permissions for Pages
        run: chmod -R +rX docs

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: docs

      - name: Publish Docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
